/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 1;
  /** RegularExpression Id. */
  int NUM = 2;
  /** RegularExpression Id. */
  int EXPOP = 3;
  /** RegularExpression Id. */
  int PLUSOP = 4;
  /** RegularExpression Id. */
  int MULOP = 5;
  /** RegularExpression Id. */
  int MINUSOP = 6;
  /** RegularExpression Id. */
  int DIVOP = 7;
  /** RegularExpression Id. */
  int OPEN = 8;
  /** RegularExpression Id. */
  int CLOSE = 9;
  /** RegularExpression Id. */
  int EQOP = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DIGIT>",
    "<NUM>",
    "\"^\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
